package http2

const (
	FLAG_NO          = 0x00
	FLAG_ACK         = 0x01
	FLAG_END_STREAM  = 0x01
	FLAG_END_HEADERS = 0x04
	FLAG_PADDED      = 0x08
	FLAG_PRIORITY    = 0x20
)

const (
	TYPE_DATA = iota
	TYPE_HEADERS
	TYPE_PRIORITY
	TYPE_RST_STREAM
	TYPE_SETTINGS
	TYPE_PING
	TYPE_GOAWAY
	TYPE_WINDOW_UPDATE
	TYPE_CONTINUATION
)

const (
	SETTINGS_NO = iota
	SETTINGS_HEADER_TABLE_SIZE
	SETTINGS_ENABLE_PUSE
	SETTINGS_MAX_CONCURRENT_STREAMS
	SETTINGS_INITIAL_WINDOW_SIZE
	SETTINGS_MAX_FRAME_SIZE
	SETTINGS_MAX_HEADER_LIST_SIZE
)

const (
	NO_ERROR = iota
	PROTOCOL_ERROR
	INTERNAL_ERROR
	FLOW_CONTROL_ERROR
	SETTINGS_TIMEOUT
	STREAM_CLOSED
	FRAME_SIZE_ERROR
	REFUSED_STREAM
	CANCEL
	COMPRESSION_ERROR
	CONNECT_ERROR
	ENHANCE_YOUR_CALM
	INADEQUATE_SECURITY
	HTTP_1_1_REQUIRED
)
