package http2

const (
	FLAG_NO          = 0x00
	FLAG_ACK         = 0x01
	FLAG_END_STREAM  = 0x01
	FLAG_END_HEADERS = 0x04
	FLAG_PADDED      = 0x08
	FLAG_PRIORITY    = 0x20
)

const (
	TYPE_DATA = iota
	TYPE_HEADERS
	TYPE_PRIORITY
	TYPE_RST_STREAM
	TYPE_SETTINGS
	TYPE_PING
	TYPE_GOAWAY
	TYPE_WINDOW_UPDATE
	TYPE_CONTINUATION
)
