package http2

// PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n
var CONNECTION_PREFACE = []byte{0x50, 0x52, 0x49, 0x20, 0x2a, 0x20, 0x48, 0x54, 0x54, 0x50, 0x2f, 0x32, 0x2e, 0x30, 0x0d, 0x0a, 0x0d, 0x0a, 0x53, 0x4d, 0x0d, 0x0a, 0x0d, 0x0a}

const (
	FLAG_NO          = 0x00
	FLAG_ACK         = 0x01
	FLAG_END_STREAM  = 0x01
	FLAG_END_HEADERS = 0x04
	FLAG_PADDED      = 0x08
	FLAG_PRIORITY    = 0x20
)

const (
	TYPE_DATA = iota
	TYPE_HEADERS
	TYPE_PRIORITY
	TYPE_RST_STREAM
	TYPE_SETTINGS
	TYPE_PING
	TYPE_GOAWAY
	TYPE_WINDOW_UPDATE
	TYPE_CONTINUATION
)

const (
	SETTINGS_NO = iota
	SETTINGS_HEADER_TABLE_SIZE
	SETTINGS_ENABLE_PUSE
	SETTINGS_MAX_CONCURRENT_STREAMS
	SETTINGS_INITIAL_WINDOW_SIZE
	SETTINGS_MAX_FRAME_SIZE
	SETTINGS_MAX_HEADER_LIST_SIZE
)

const (
	NO_ERROR = iota
	PROTOCOL_ERROR
	INTERNAL_ERROR
	FLOW_CONTROL_ERROR
	SETTINGS_TIMEOUT
	STREAM_CLOSED
	FRAME_SIZE_ERROR
	REFUSED_STREAM
	CANCEL
	COMPRESSION_ERROR
	CONNECT_ERROR
	ENHANCE_YOUR_CALM
	INADEQUATE_SECURITY
	HTTP_1_1_REQUIRED
)
